language: node_js # 언어는 node_js
node_js:
  - "10.14" # node_js에 버전 10.14
before_install: # 패키지를 다운로드 받기 전
  - npm update # npm 패키지를 업데이트
  - cd ./client
branches:
  only:
    - master
notifications: # 성공 실패 여부 알림
  email:
    recipients:
      - xxx@xxx.com
