version: "2"

services:
  bless-music-studio-server:
    image: bless-music-studio-image
    volumes:
      - /home/ec2-user/deploy/Bless-Music-Studio:/deploy/Bless-Music-Studio
    ports:
      - "3002:3000"
